"""added spots table

Revision ID: 4f20ee77c00e
Revises: 
Create Date: 2020-02-22 00:40:58.921281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f20ee77c00e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'spots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('surfline_id', sa.String(), nullable=False),
        sa.Column('surfline_spot_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('surfline_id')
    )
    op.create_index(op.f('ix_spots_surfline_spot_id'), 'spots', ['surfline_spot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spots_surfline_spot_id'), table_name='spots')
    op.drop_table('spots')
    # ### end Alembic commands ###
