"""added forecasts table

Revision ID: a17941a522a1
Revises: 4f20ee77c00e
Create Date: 2020-02-22 00:46:51.489611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17941a522a1'
down_revision = '4f20ee77c00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'forecasts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('spot_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('am_min_height', sa.Integer(), nullable=False),
        sa.Column('am_max_height', sa.Integer(), nullable=False),
        sa.Column('am_rating', sa.String(), nullable=False),
        sa.Column('pm_min_height', sa.Integer(), nullable=False),
        sa.Column('pm_max_height', sa.Integer(), nullable=False),
        sa.Column('pm_rating', sa.String(), nullable=False),
        sa.Column('swell1_height', sa.Float(), nullable=False),
        sa.Column('swell1_period', sa.Integer(), nullable=False),
        sa.Column('swell1_direction', sa.Float(), nullable=False),
        sa.Column('swell2_height', sa.Float(), nullable=False),
        sa.Column('swell2_period', sa.Integer(), nullable=False),
        sa.Column('swell2_direction', sa.Float(), nullable=False),
        sa.Column('swell3_height', sa.Float(), nullable=False),
        sa.Column('swell3_period', sa.Integer(), nullable=False),
        sa.Column('swell3_direction', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_spot_id'),
                    'forecasts', ['spot_id'], unique=False)
    op.create_index(op.f('ix_forecasts_timestamp'),
                    'forecasts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_timestamp'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_spot_id'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
