'''make spot name not unique

Revision ID: b22cca33828c
Revises: 41fa67432f6c
Create Date: 2020-02-24 12:18:59.208635

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22cca33828c'
down_revision = '41fa67432f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spots_name_key', 'spots', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('spots_name_key', 'spots', ['name'])
    # ### end Alembic commands ###
